apiVersion: v1
kind: Endpoints
metadata:
  name: kafka
subsets:
  - addresses:
      - ip: 10.20.1.22 # change to your kafka server ip
    ports:
      - port: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-config
data:
  config.ini: |
    [POD]
    LABEL=app=oai-gnb

    [KAFKA]
    SERVER=kafka:9092
    USERNAME=test
    PASSWORD=test
    TOPIC=test
    GROUP_ID=test

    [DATABASE]
    HOST=127.0.0.1
    PORT=31000
    USER=root
    PASSWORD=1234
    DB=gnb_info

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      name: monitor
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: monitor-service
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_PATH
              value: /workdir/config/config.ini
            - name: KUBE_CONFIG
              value: /workdir/config/config
          volumeMounts:
            - mountPath: /workdir/config/config.ini
              name: config
            - mountPath: /workdir/config/config
              name: k8sconfig
      volumes:
        - name: config
          configMap:
            name: monitor-config
        - name: k8sconfig
          hostPath:
            path: /home/ubuntu/.kube/config # change to your k8s config path
